package gov.healthit.chpl.entity;

import gov.healthit.chpl.entity.CertificationBody;
import gov.healthit.chpl.entity.TestingLab;
import gov.healthit.chpl.entity.Vendor;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: address.
 * 
 *
 * @author autogenerated
 */

@Entity
@Table(name = "address", catalog = "openchpl", schema = "openchpl")
public class Address implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = -2487128076959820669L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Long> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
	
	/** hashCode temporary storage. */
	private volatile Long hashCode;
	

	/** Field mapping. */
	private Set<CertificationBody> certificationBodies = new HashSet<CertificationBody>();

	/** Field mapping. */
	private String city;
	/** Field mapping. */
	private String country;
	/** Field mapping. */
	private Date creationDate;
	/** Field mapping. */
	private Boolean deleted;
	/** Field mapping. */
	private Long id;
	/** Field mapping. */
	private Date lastModifiedDate;
	/** Field mapping. */
	private Long lastModifiedUser;
	/** Field mapping. */
	private String region;
	/** Field mapping. */
	private String streetLine1;
	/** Field mapping. */
	private String streetLine2;
	/** Field mapping. */
	private Set<TestingLab> testingLabs = new HashSet<TestingLab>();

	/** Field mapping. */
	private Set<Vendor> vendors = new HashSet<Vendor>();

	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Address() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Address(Long id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param city String object;
	 * @param country String object;
	 * @param creationDate Date object;
	 * @param deleted Boolean object;
	 * @param id Long object;
	 * @param lastModifiedDate Date object;
	 * @param lastModifiedUser Long object;
	 * @param region String object;
	 * @param streetLine1 String object;
	 */
	public Address(String city, String country, Date creationDate, 					
			Boolean deleted, Long id, Date lastModifiedDate, 					
			Long lastModifiedUser, String region, String streetLine1) {

		this.city = city;
		this.country = country;
		this.creationDate = creationDate;
		this.deleted = deleted;
		this.id = id;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedUser = lastModifiedUser;
		this.region = region;
		this.streetLine1 = streetLine1;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Address.class;
	}
 

	 /**
	 * Return the value associated with the column: certificationBody.
	 * @return A Set&lt;CertificationBody&gt; object (this.certificationBody)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "address"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@Column( name = "address_id", nullable = false  )
	public Set<CertificationBody> getCertificationBodies() {
		return this.certificationBodies;
		
	}
	
	/**
	 * Adds a bi-directional link of type CertificationBody to the certificationBodies set.
	 * @param certificationBody item to add
	 */
	public void addCertificationBody(CertificationBody certificationBody) {
		certificationBody.setAddress(this);
		this.certificationBodies.add(certificationBody);
	}

  
	 /**  
	 * Set the value related to the column: certificationBody.
	 * @param certificationBody the certificationBody value you wish to set
	 */
	public void setCertificationBodies(final Set<CertificationBody> certificationBody) {
		this.certificationBodies = certificationBody;
	}

	 /**
	 * Return the value associated with the column: city.
	 * @return A String object (this.city)
	 */
	@Basic( optional = false )
	@Column( nullable = false, length = 250  )
	public String getCity() {
		return this.city;
		
	}
	

  
	 /**  
	 * Set the value related to the column: city.
	 * @param city the city value you wish to set
	 */
	public void setCity(final String city) {
		this.city = city;
	}

	 /**
	 * Return the value associated with the column: country.
	 * @return A String object (this.country)
	 */
	@Basic( optional = false )
	@Column( nullable = false, length = 250  )
	public String getCountry() {
		return this.country;
		
	}
	

  
	 /**  
	 * Set the value related to the column: country.
	 * @param country the country value you wish to set
	 */
	public void setCountry(final String country) {
		this.country = country;
	}

	 /**
	 * Return the value associated with the column: creationDate.
	 * @return A Date object (this.creationDate)
	 */
	@Basic( optional = false )
	@Column( name = "creation_date", nullable = false  )
	public Date getCreationDate() {
		return this.creationDate;
		
	}
	

  
	 /**  
	 * Set the value related to the column: creationDate.
	 * @param creationDate the creationDate value you wish to set
	 */
	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	 /**
	 * Return the value associated with the column: deleted.
	 * @return A Boolean object (this.deleted)
	 */
	@Basic( optional = false )
	@Column( nullable = false  )
	public Boolean isDeleted() {
		return this.deleted;
		
	}
	

  
	 /**  
	 * Set the value related to the column: deleted.
	 * @param deleted the deleted value you wish to set
	 */
	public void setDeleted(final Boolean deleted) {
		this.deleted = deleted;
	}

	 /**
	 * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "addressAddress_idGenerator")
	@Basic( optional = false )
	@Column( name = "address_id", nullable = false  )
	@SequenceGenerator(name = "addressAddress_idGenerator", sequenceName = "openchpl.openchpl.address_address_id_seq", schema = "openchpl", catalog = "openchpl")
	public Long getId() {
		return this.id;
		
	}
	

  
	 /**  
	 * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Long id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0L) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

	 /**
	 * Return the value associated with the column: lastModifiedDate.
	 * @return A Date object (this.lastModifiedDate)
	 */
	@Basic( optional = false )
	@Column( name = "last_modified_date", nullable = false  )
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
		
	}
	

  
	 /**  
	 * Set the value related to the column: lastModifiedDate.
	 * @param lastModifiedDate the lastModifiedDate value you wish to set
	 */
	public void setLastModifiedDate(final Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	 /**
	 * Return the value associated with the column: lastModifiedUser.
	 * @return A Long object (this.lastModifiedUser)
	 */
	@Basic( optional = false )
	@Column( name = "last_modified_user", nullable = false  )
	public Long getLastModifiedUser() {
		return this.lastModifiedUser;
		
	}
	

  
	 /**  
	 * Set the value related to the column: lastModifiedUser.
	 * @param lastModifiedUser the lastModifiedUser value you wish to set
	 */
	public void setLastModifiedUser(final Long lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	 /**
	 * Return the value associated with the column: region.
	 * @return A String object (this.region)
	 */
	@Basic( optional = false )
	@Column( nullable = false, length = 250  )
	public String getRegion() {
		return this.region;
		
	}
	

  
	 /**  
	 * Set the value related to the column: region.
	 * @param region the region value you wish to set
	 */
	public void setRegion(final String region) {
		this.region = region;
	}

	 /**
	 * Return the value associated with the column: streetLine1.
	 * @return A String object (this.streetLine1)
	 */
	@Basic( optional = false )
	@Column( name = "street_line_1", nullable = false, length = 250  )
	public String getStreetLine1() {
		return this.streetLine1;
		
	}
	

  
	 /**  
	 * Set the value related to the column: streetLine1.
	 * @param streetLine1 the streetLine1 value you wish to set
	 */
	public void setStreetLine1(final String streetLine1) {
		this.streetLine1 = streetLine1;
	}

	 /**
	 * Return the value associated with the column: streetLine2.
	 * @return A String object (this.streetLine2)
	 */
	@Basic( optional = true )
	@Column( name = "street_line_2", length = 250  )
	public String getStreetLine2() {
		return this.streetLine2;
		
	}
	

  
	 /**  
	 * Set the value related to the column: streetLine2.
	 * @param streetLine2 the streetLine2 value you wish to set
	 */
	public void setStreetLine2(final String streetLine2) {
		this.streetLine2 = streetLine2;
	}

	 /**
	 * Return the value associated with the column: testingLab.
	 * @return A Set&lt;TestingLab&gt; object (this.testingLab)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "address"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@Column( name = "address_id", nullable = false  )
	public Set<TestingLab> getTestingLabs() {
		return this.testingLabs;
		
	}
	
	/**
	 * Adds a bi-directional link of type TestingLab to the testingLabs set.
	 * @param testingLab item to add
	 */
	public void addTestingLab(TestingLab testingLab) {
		testingLab.setAddress(this);
		this.testingLabs.add(testingLab);
	}

  
	 /**  
	 * Set the value related to the column: testingLab.
	 * @param testingLab the testingLab value you wish to set
	 */
	public void setTestingLabs(final Set<TestingLab> testingLab) {
		this.testingLabs = testingLab;
	}

	 /**
	 * Return the value associated with the column: vendor.
	 * @return A Set&lt;Vendor&gt; object (this.vendor)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "address"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@Column( name = "address_id", nullable = false  )
	public Set<Vendor> getVendors() {
		return this.vendors;
		
	}
	
	/**
	 * Adds a bi-directional link of type Vendor to the vendors set.
	 * @param vendor item to add
	 */
	public void addVendor(Vendor vendor) {
		vendor.setAddress(this);
		this.vendors.add(vendor);
	}

  
	 /**  
	 * Set the value related to the column: vendor.
	 * @param vendor the vendor value you wish to set
	 */
	public void setVendors(final Set<Vendor> vendor) {
		this.vendors = vendor;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Address clone() throws CloneNotSupportedException {
		
        final Address copy = (Address)super.clone();

		if (this.getCertificationBodies() != null) {
			copy.getCertificationBodies().addAll(this.getCertificationBodies());
		}
		copy.setCity(this.getCity());
		copy.setCountry(this.getCountry());
		copy.setCreationDate(this.getCreationDate());
		copy.setDeleted(this.isDeleted());
		copy.setId(this.getId());
		copy.setLastModifiedDate(this.getLastModifiedDate());
		copy.setLastModifiedUser(this.getLastModifiedUser());
		copy.setRegion(this.getRegion());
		copy.setStreetLine1(this.getStreetLine1());
		copy.setStreetLine2(this.getStreetLine2());
		if (this.getTestingLabs() != null) {
			copy.getTestingLabs().addAll(this.getTestingLabs());
		}
		if (this.getVendors() != null) {
			copy.getVendors().addAll(this.getVendors());
		}
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("city: " + this.getCity() + ", ");
		sb.append("country: " + this.getCountry() + ", ");
		sb.append("creationDate: " + this.getCreationDate() + ", ");
		sb.append("deleted: " + this.isDeleted() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("lastModifiedDate: " + this.getLastModifiedDate() + ", ");
		sb.append("lastModifiedUser: " + this.getLastModifiedUser() + ", ");
		sb.append("region: " + this.getRegion() + ", ");
		sb.append("streetLine1: " + this.getStreetLine1() + ", ");
		sb.append("streetLine2: " + this.getStreetLine2() + ", ");
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Address that; 
		try {
			that = (Address) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getCity() == null) && (that.getCity() == null)) || (getCity() != null && getCity().equals(that.getCity())));
		result = result && (((getCountry() == null) && (that.getCountry() == null)) || (getCountry() != null && getCountry().equals(that.getCountry())));
		result = result && (((getCreationDate() == null) && (that.getCreationDate() == null)) || (getCreationDate() != null && getCreationDate().equals(that.getCreationDate())));
		result = result && (((isDeleted() == null) && (that.isDeleted() == null)) || (isDeleted() != null && isDeleted().equals(that.isDeleted())));
		result = result && (((getLastModifiedDate() == null) && (that.getLastModifiedDate() == null)) || (getLastModifiedDate() != null && getLastModifiedDate().equals(that.getLastModifiedDate())));
		result = result && (((getLastModifiedUser() == null) && (that.getLastModifiedUser() == null)) || (getLastModifiedUser() != null && getLastModifiedUser().equals(that.getLastModifiedUser())));
		result = result && (((getRegion() == null) && (that.getRegion() == null)) || (getRegion() != null && getRegion().equals(that.getRegion())));
		result = result && (((getStreetLine1() == null) && (that.getStreetLine1() == null)) || (getStreetLine1() != null && getStreetLine1().equals(that.getStreetLine1())));
		result = result && (((getStreetLine2() == null) && (that.getStreetLine2() == null)) || (getStreetLine2() != null && getStreetLine2().equals(that.getStreetLine2())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Long newHashCode = null;

					if ( getId() != null ) {
					newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0L) {
							newHashCode = getId();
						} else {
							newHashCode = (long) super.hashCode();

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
		return (int) (this.hashCode & 0xffffff);
	}
	

	
}
