package gov.healthit.chpl.entity;

import gov.healthit.chpl.auth.user.UserContactEntity;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;


/** 
 * Object mapping for hibernate-handled table: atl_contact_map.
 * 
 *
 * @author autogenerated
 */

@Embeddable
public class AtlContactMapPK implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = -1807132212423889382L;

	

	/** Field mapping. */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@JoinColumn(name = "contact_id", nullable = false , insertable = false, updatable = false )
	private Contact contact;

	/** Field mapping. */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@JoinColumn(name = "testing_lab_id_testing_lab", nullable = false , insertable = false, updatable = false )
	private TestingLab testingLabIdTestingLab;

 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return AtlContactMapPK.class;
	}
 

	 /**
	 * Return the value associated with the column: contact.
	 * @return A Contact object (this.contact)
	 */
	public Contact getContact() {
		return this.contact;
		
	}
	

  
	 /**  
	 * Set the value related to the column: contact.
	 * @param contact2 the contact value you wish to set
	 */
	public void setContact(final Contact contact2) {
		this.contact = contact2;
	}

	 /**
	 * Return the value associated with the column: testingLabIdTestingLab.
	 * @return A TestingLab object (this.testingLabIdTestingLab)
	 */
	public TestingLab getTestingLabIdTestingLab() {
		return this.testingLabIdTestingLab;
		
	}
	

  
	 /**  
	 * Set the value related to the column: testingLabIdTestingLab.
	 * @param testingLabIdTestingLab the testingLabIdTestingLab value you wish to set
	 */
	public void setTestingLabIdTestingLab(final TestingLab testingLabIdTestingLab) {
		this.testingLabIdTestingLab = testingLabIdTestingLab;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public AtlContactMapPK clone() throws CloneNotSupportedException {
		
        final AtlContactMapPK copy = (AtlContactMapPK)super.clone();

		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		if (aThat == null)  {
			 return false;
		}
		
		final AtlContactMapPK that; 
		try {
			that = (AtlContactMapPK) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((getContact() == null) && (that.getContact() == null)) || (getContact() != null && getContact().getId().equals(that.getContact().getId())));	
		result = result && (((getTestingLabIdTestingLab() == null) && (that.getTestingLabIdTestingLab() == null)) || (getTestingLabIdTestingLab() != null && getTestingLabIdTestingLab().getId().equals(that.getTestingLabIdTestingLab().getId())));	
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
	int hash = 0;
		hash = hash + getContact().hashCode();
		hash = hash + getTestingLabIdTestingLab().hashCode();
	return hash;
	}
	

	
}
