package gov.healthit.chpl.entity;

import gov.healthit.chpl.entity.CertifiedProductCqmEditionMap;
import gov.healthit.chpl.entity.CqmCriterion;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: cqm_edition.
 * 
 *
 * @author autogenerated
 */

@Entity
@Table(name = "cqm_edition", catalog = "openchpl", schema = "openchpl")
public class CqmEdition implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = -5403669520776600083L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Long> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
	
	/** hashCode temporary storage. */
	private volatile Long hashCode;
	

	/** Field mapping. */
	private Set<CertifiedProductCqmEditionMap> certifiedProductCqmEditionMaps = new HashSet<CertifiedProductCqmEditionMap>();

	/** Field mapping. */
	private Set<CqmCriterion> cqmCriterions = new HashSet<CqmCriterion>();

	/** Field mapping. */
	private Date creationDate;
	/** Field mapping. */
	private Boolean deleted;
	/** Field mapping. */
	private String edition;
	/** Field mapping. */
	private Long id;
	/** Field mapping. */
	private Date lastModifiedDate;
	/** Field mapping. */
	private Long lastModifiedUser;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public CqmEdition() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public CqmEdition(Long id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param creationDate Date object;
	 * @param deleted Boolean object;
	 * @param id Long object;
	 * @param lastModifiedDate Date object;
	 * @param lastModifiedUser Long object;
	 */
	public CqmEdition(Date creationDate, Boolean deleted, Long id, 					
			Date lastModifiedDate, Long lastModifiedUser) {

		this.creationDate = creationDate;
		this.deleted = deleted;
		this.id = id;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedUser = lastModifiedUser;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return CqmEdition.class;
	}
 

	 /**
	 * Return the value associated with the column: certifiedProductCqmEditionMap.
	 * @return A Set&lt;CertifiedProductCqmEditionMap&gt; object (this.certifiedProductCqmEditionMap)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "cqmEdition"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@Column( name = "cqm_edition_id", nullable = false  )
	public Set<CertifiedProductCqmEditionMap> getCertifiedProductCqmEditionMaps() {
		return this.certifiedProductCqmEditionMaps;
		
	}
	
	/**
	 * Adds a bi-directional link of type CertifiedProductCqmEditionMap to the certifiedProductCqmEditionMaps set.
	 * @param certifiedProductCqmEditionMap item to add
	 */
	public void addCertifiedProductCqmEditionMap(CertifiedProductCqmEditionMap certifiedProductCqmEditionMap) {
		certifiedProductCqmEditionMap.setCqmEdition(this);
		this.certifiedProductCqmEditionMaps.add(certifiedProductCqmEditionMap);
	}

  
	 /**  
	 * Set the value related to the column: certifiedProductCqmEditionMap.
	 * @param certifiedProductCqmEditionMap the certifiedProductCqmEditionMap value you wish to set
	 */
	public void setCertifiedProductCqmEditionMaps(final Set<CertifiedProductCqmEditionMap> certifiedProductCqmEditionMap) {
		this.certifiedProductCqmEditionMaps = certifiedProductCqmEditionMap;
	}

	 /**
	 * Return the value associated with the column: cqmCriterion.
	 * @return A Set&lt;CqmCriterion&gt; object (this.cqmCriterion)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "cqmEdition"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@Column( name = "cqm_edition_id", nullable = false  )
	public Set<CqmCriterion> getCqmCriterions() {
		return this.cqmCriterions;
		
	}
	
	/**
	 * Adds a bi-directional link of type CqmCriterion to the cqmCriterions set.
	 * @param cqmCriterion item to add
	 */
	public void addCqmCriterion(CqmCriterion cqmCriterion) {
		cqmCriterion.setCqmEdition(this);
		this.cqmCriterions.add(cqmCriterion);
	}

  
	 /**  
	 * Set the value related to the column: cqmCriterion.
	 * @param cqmCriterion the cqmCriterion value you wish to set
	 */
	public void setCqmCriterions(final Set<CqmCriterion> cqmCriterion) {
		this.cqmCriterions = cqmCriterion;
	}

	 /**
	 * Return the value associated with the column: creationDate.
	 * @return A Date object (this.creationDate)
	 */
	@Basic( optional = false )
	@Column( name = "creation_date", nullable = false  )
	public Date getCreationDate() {
		return this.creationDate;
		
	}
	

  
	 /**  
	 * Set the value related to the column: creationDate.
	 * @param creationDate the creationDate value you wish to set
	 */
	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	 /**
	 * Return the value associated with the column: deleted.
	 * @return A Boolean object (this.deleted)
	 */
	@Basic( optional = false )
	@Column( nullable = false  )
	public Boolean isDeleted() {
		return this.deleted;
		
	}
	

  
	 /**  
	 * Set the value related to the column: deleted.
	 * @param deleted the deleted value you wish to set
	 */
	public void setDeleted(final Boolean deleted) {
		this.deleted = deleted;
	}

	 /**
	 * Return the value associated with the column: edition.
	 * @return A String object (this.edition)
	 */
	@Basic( optional = true )
	@Column( length = 10  )
	public String getEdition() {
		return this.edition;
		
	}
	

  
	 /**  
	 * Set the value related to the column: edition.
	 * @param edition the edition value you wish to set
	 */
	public void setEdition(final String edition) {
		this.edition = edition;
	}

	 /**
	 * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cqmEditionCqm_edition_idGenerator")
	@Basic( optional = false )
	@Column( name = "cqm_edition_id", nullable = false  )
	@SequenceGenerator(name = "cqmEditionCqm_edition_idGenerator", sequenceName = "openchpl.openchpl.cqm_edition_cqm_edition_id_seq", schema = "openchpl", catalog = "openchpl")
	public Long getId() {
		return this.id;
		
	}
	

  
	 /**  
	 * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Long id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0L) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

	 /**
	 * Return the value associated with the column: lastModifiedDate.
	 * @return A Date object (this.lastModifiedDate)
	 */
	@Basic( optional = false )
	@Column( name = "last_modified_date", nullable = false  )
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
		
	}
	

  
	 /**  
	 * Set the value related to the column: lastModifiedDate.
	 * @param lastModifiedDate the lastModifiedDate value you wish to set
	 */
	public void setLastModifiedDate(final Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	 /**
	 * Return the value associated with the column: lastModifiedUser.
	 * @return A Long object (this.lastModifiedUser)
	 */
	@Basic( optional = false )
	@Column( name = "last_modified_user", nullable = false  )
	public Long getLastModifiedUser() {
		return this.lastModifiedUser;
		
	}
	

  
	 /**  
	 * Set the value related to the column: lastModifiedUser.
	 * @param lastModifiedUser the lastModifiedUser value you wish to set
	 */
	public void setLastModifiedUser(final Long lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public CqmEdition clone() throws CloneNotSupportedException {
		
        final CqmEdition copy = (CqmEdition)super.clone();

		if (this.getCertifiedProductCqmEditionMaps() != null) {
			copy.getCertifiedProductCqmEditionMaps().addAll(this.getCertifiedProductCqmEditionMaps());
		}
		if (this.getCqmCriterions() != null) {
			copy.getCqmCriterions().addAll(this.getCqmCriterions());
		}
		copy.setCreationDate(this.getCreationDate());
		copy.setDeleted(this.isDeleted());
		copy.setEdition(this.getEdition());
		copy.setId(this.getId());
		copy.setLastModifiedDate(this.getLastModifiedDate());
		copy.setLastModifiedUser(this.getLastModifiedUser());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("creationDate: " + this.getCreationDate() + ", ");
		sb.append("deleted: " + this.isDeleted() + ", ");
		sb.append("edition: " + this.getEdition() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("lastModifiedDate: " + this.getLastModifiedDate() + ", ");
		sb.append("lastModifiedUser: " + this.getLastModifiedUser());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final CqmEdition that; 
		try {
			that = (CqmEdition) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getCreationDate() == null) && (that.getCreationDate() == null)) || (getCreationDate() != null && getCreationDate().equals(that.getCreationDate())));
		result = result && (((isDeleted() == null) && (that.isDeleted() == null)) || (isDeleted() != null && isDeleted().equals(that.isDeleted())));
		result = result && (((getEdition() == null) && (that.getEdition() == null)) || (getEdition() != null && getEdition().equals(that.getEdition())));
		result = result && (((getLastModifiedDate() == null) && (that.getLastModifiedDate() == null)) || (getLastModifiedDate() != null && getLastModifiedDate().equals(that.getLastModifiedDate())));
		result = result && (((getLastModifiedUser() == null) && (that.getLastModifiedUser() == null)) || (getLastModifiedUser() != null && getLastModifiedUser().equals(that.getLastModifiedUser())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Long newHashCode = null;

					if ( getId() != null ) {
					newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0L) {
							newHashCode = getId();
						} else {
							newHashCode = (long) super.hashCode();

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
		return (int) (this.hashCode & 0xffffff);
	}
	

	
}
