package gov.healthit.chpl.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;


/** 
 * Object mapping for hibernate-handled table: certified_product.
 * A product that has been Certified
 *
 * @author autogenerated / cwatson
 */

@Entity
@Table(name = "pending_certified_product")
public class PendingCertifiedProductEntity {
	
	/**
	 * fields we generate mostly from spreadsheet values
	 */
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic( optional = false )
	@Column( name = "pending_certified_product_id", nullable = false  )
	private Long id;
    
    @Column(name = "practice_type_id")
    private Long practiceTypeId;
    
    @Column(name = "vendor_id")
    private Long developerId;
    
    @Basic( optional = true )
	@OneToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_address_id", unique=true, nullable = true)
	private AddressEntity developerAddress;
    
    @Column(name = "product_id")
    private Long productId;
    
    @Column(name = "product_version_id")
    private Long productVersionId;
    
    @Column(name = "certification_edition_id")
    private Long certificationEditionId;
    
    @Column(name = "certification_body_id")
    private Long certificationBodyId;
    
    @Column(name = "product_classification_id")
    private Long productClassificationId;
    
    @Column(name = "additional_software_id")
    private Long additionalSoftwareId;
    
	@Basic(optional = false) 
	@Column( name = "certification_status_id" , nullable = false)
	private Long status;
	
    /**
    * fields directly from the spreadsheet
    **/
    @Column(name = "unique_id")
    private String uniqueId;
    
    @Column(name = "record_status")
    private String recordStatus;
    
    @Column(name = "practice_type")
    private String practiceType;
    
    @Column(name="vendor_name")
    private String developerName;
    
    @Column(name = "product_name")
    private String productName;
    
    @Column(name = "product_version")
    private String productVersion;
    
    @Column(name = "certification_edition")
    private String certificationEdition;
    
    @Column(name = "acb_certification_id")
    private String acbCertificationId;
    
    @Column(name = "certification_body_name")
    private String certificationBodyName;
    
    @Column(name = "product_classification_name")
    private String productClassificationName;
    
    //TODO: no field for this one
    @Column(name = "product_classification_module")
    private String productClassificationModule;
    
    @Column(name = "certification_date")
    private Date certificationDate;
    
    @Column(name = "vendor_street_address")
    private String developerStreetAddress;
    
    @Column(name = "vendor_city")
    private String developerCity;
    
    @Column(name = "vendor_state")
    private String developerState;
    
    @Column(name = "vendor_zip_code")
    private String developerZipCode;
    
    @Column(name = "vendor_website")
    private String developerWebsite;
    
    //TODO: maps to nothing
    @Column(name = "vendor_email")
    private String developerEmail;
    
    @Column(name = "additional_software")
    private String additionalSoftware;
    
    //TODO: maps to nothing
    @Column(name = "upload_notes")
    private String uploadNotes;
    
    @Column(name = "test_report_url")
    private String reportFileLocation;
    
	@Column(name = "ics")
	private String ics;
	
	@Column(name = "sed")
	private Boolean sedTesting;
	
	@Column(name = "qms")
	private Boolean qmsTesting;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy="pendingCertifiedProductId")
	@Basic( optional = false )
	@Column( name = "pending_certified_product_id", nullable = false  )
	private Set<PendingCertificationCriterionEntity> certificationCriterion;
    
	@OneToMany(fetch = FetchType.LAZY, mappedBy="pendingCertifiedProductId")
	@Basic( optional = false )
	@Column( name = "pending_certified_product_id", nullable = false  )
	private Set<PendingCqmCriterionEntity> cqmCriterion;
	
	@Basic( optional = false )
	@Column( name = "last_modified_date", nullable = false  )
	private Date lastModifiedDate;
	
	@Basic( optional = false )
	@Column( name = "last_modified_user", nullable = false  )
	private Long lastModifiedUser;
	
	@Basic( optional = false )
	@Column( name = "creation_date", nullable = false  )
	private Date creationDate;
	
	@Basic( optional = false )
	@Column(name = "deleted", nullable = false  )
	private Boolean deleted;
	
	public PendingCertifiedProductEntity() {
		certificationCriterion = new HashSet<PendingCertificationCriterionEntity>();
		cqmCriterion = new HashSet<PendingCqmCriterionEntity>();
	} 

	public PendingCertifiedProductEntity(Long id) {
		this.id = id;
		certificationCriterion = new HashSet<PendingCertificationCriterionEntity>();
		cqmCriterion = new HashSet<PendingCqmCriterionEntity>();
	}
	
	@Transient
	public Class<?> getClassType() {
		return PendingCertifiedProductEntity.class;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getPracticeTypeId() {
		return practiceTypeId;
	}

	public void setPracticeTypeId(Long practiceTypeId) {
		this.practiceTypeId = practiceTypeId;
	}

	public Long getDeveloperId() {
		return developerId;
	}

	public void setDeveloperId(Long developerId) {
		this.developerId = developerId;
	}

	public Long getProductId() {
		return productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public Long getProductVersionId() {
		return productVersionId;
	}

	public void setProductVersionId(Long productVersionId) {
		this.productVersionId = productVersionId;
	}

	public Long getCertificationEditionId() {
		return certificationEditionId;
	}

	public void setCertificationEditionId(Long certificationEditionId) {
		this.certificationEditionId = certificationEditionId;
	}

	public Long getCertificationBodyId() {
		return certificationBodyId;
	}

	public void setCertificationBodyId(Long certificationBodyId) {
		this.certificationBodyId = certificationBodyId;
	}

	public Long getProductClassificationId() {
		return productClassificationId;
	}

	public void setProductClassificationId(Long productClassificationId) {
		this.productClassificationId = productClassificationId;
	}

	public String getUniqueId() {
		return uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public String getRecordStatus() {
		return recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	public String getPracticeType() {
		return practiceType;
	}

	public void setPracticeType(String practiceType) {
		this.practiceType = practiceType;
	}

	public String getDeveloperName() {
		return developerName;
	}

	public void setDeveloperName(String developerName) {
		this.developerName = developerName;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductVersion() {
		return productVersion;
	}

	public void setProductVersion(String productVersion) {
		this.productVersion = productVersion;
	}

	public String getCertificationEdition() {
		return certificationEdition;
	}

	public void setCertificationEdition(String certificationEdition) {
		this.certificationEdition = certificationEdition;
	}

	public String getAcbCertificationId() {
		return acbCertificationId;
	}

	public void setAcbCertificationId(String acbCertificationId) {
		this.acbCertificationId = acbCertificationId;
	}

	public String getCertificationBodyName() {
		return certificationBodyName;
	}

	public void setCertificationBodyName(String certificationBodyName) {
		this.certificationBodyName = certificationBodyName;
	}

	public String getProductClassificationName() {
		return productClassificationName;
	}

	public void setProductClassificationName(String productClassificationName) {
		this.productClassificationName = productClassificationName;
	}

	public String getProductClassificationModule() {
		return productClassificationModule;
	}

	public void setProductClassificationModule(String productClassificationModule) {
		this.productClassificationModule = productClassificationModule;
	}

	public Date getCertificationDate() {
		return certificationDate;
	}

	public void setCertificationDate(Date certificationDate) {
		this.certificationDate = certificationDate;
	}

	public String getDeveloperStreetAddress() {
		return developerStreetAddress;
	}

	public void setDeveloperStreetAddress(String developerStreetAddress) {
		this.developerStreetAddress = developerStreetAddress;
	}

	public String getDeveloperCity() {
		return developerCity;
	}

	public void setDeveloperCity(String developerCity) {
		this.developerCity = developerCity;
	}

	public String getDeveloperState() {
		return developerState;
	}

	public void setDeveloperState(String developerState) {
		this.developerState = developerState;
	}

	public String getDeveloperZipCode() {
		return developerZipCode;
	}

	public void setDeveloperZipCode(String developerZipCode) {
		this.developerZipCode = developerZipCode;
	}

	public String getDeveloperWebsite() {
		return developerWebsite;
	}

	public void setDeveloperWebsite(String developerWebsite) {
		this.developerWebsite = developerWebsite;
	}

	public String getDeveloperEmail() {
		return developerEmail;
	}

	public void setDeveloperEmail(String developerEmail) {
		this.developerEmail = developerEmail;
	}

	public String getAdditionalSoftware() {
		return additionalSoftware;
	}

	public void setAdditionalSoftware(String additionalSoftware) {
		this.additionalSoftware = additionalSoftware;
	}

	public String getUploadNotes() {
		return uploadNotes;
	}

	public void setUploadNotes(String uploadNotes) {
		this.uploadNotes = uploadNotes;
	}

	public String getReportFileLocation() {
		return reportFileLocation;
	}

	public void setReportFileLocation(String reportFileLocation) {
		this.reportFileLocation = reportFileLocation;
	}

	public Set<PendingCertificationCriterionEntity> getCertificationCriterion() {
		return certificationCriterion;
	}

	public void setCertificationCriterion(Set<PendingCertificationCriterionEntity> certificationCriterion) {
		this.certificationCriterion = certificationCriterion;
	}

	public Set<PendingCqmCriterionEntity> getCqmCriterion() {
		return cqmCriterion;
	}

	public void setCqmCriterion(Set<PendingCqmCriterionEntity> cqmCriterion) {
		this.cqmCriterion = cqmCriterion;
	}

	public AddressEntity getDeveloperAddress() {
		return developerAddress;
	}

	public void setDeveloperAddress(AddressEntity developerAddress) {
		this.developerAddress = developerAddress;
	}

	public Long getAdditionalSoftwareId() {
		return additionalSoftwareId;
	}

	public void setAdditionalSoftwareId(Long additionalSoftwareId) {
		this.additionalSoftwareId = additionalSoftwareId;
	}

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Long getLastModifiedUser() {
		return lastModifiedUser;
	}

	public void setLastModifiedUser(Long lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Long getStatus() {
		return status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getIcs() {
		return ics;
	}

	public void setIcs(String ics) {
		this.ics = ics;
	}

	public Boolean getSedTesting() {
		return sedTesting;
	}

	public void setSedTesting(Boolean sedTesting) {
		this.sedTesting = sedTesting;
	}

	public Boolean getQmsTesting() {
		return qmsTesting;
	}

	public void setQmsTesting(Boolean qmsTesting) {
		this.qmsTesting = qmsTesting;
	}
}
