package gov.healthit.chpl.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;


/** 
 * Object mapping for hibernate-handled table: product.
 * Table to store products that are submitted for developers
 *
 * @author autogenerated / cwatson
 */

@Entity
@Table(name = "product")
public class ProductEntity implements Serializable {
	private static final long serialVersionUID = -5332080900089062551L;

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic( optional = false )
	@Column( name = "product_id", nullable = false  )
	private Long id;
    
	@Basic( optional = false )
	@Column( name = "creation_date", nullable = false  )
	private Date creationDate;
	
	@Basic( optional = false )
	@Column(name = "deleted", nullable = false  )
	private Boolean deleted;
    
	@Basic( optional = false )
	@Column( name = "last_modified_date", nullable = false  )
	private Date lastModifiedDate;
	
	@Basic( optional = false )
	@Column( name = "last_modified_user", nullable = false  )
	private Long lastModifiedUser;
	
	@Basic( optional = false )
	@Size(min=1)
	@Column( name = "name")
	private String name;
	
 	@OneToMany( fetch = FetchType.LAZY, mappedBy = "productId"  )
	@Basic( optional = false )
	@Column( name = "product_id", nullable = false  )
	private Set<ProductVersionEntity> productVersions = new HashSet<ProductVersionEntity>();

	@Basic( optional = true )
	@Column( name = "report_file_location", length = 255  )
	private String reportFileLocation;
	
	@Basic( optional = false )
	@Column(name = "vendor_id", nullable = false )
	private Long developerId;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public ProductEntity() {
		// Default constructor
	}

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public ProductEntity(Long id) {
		this.id = id;
	} 

 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return ProductEntity.class;
	}
 

	 /**
	 * Return the value associated with the column: creationDate.
	 * @return A Date object (this.creationDate)
	 */
	public Date getCreationDate() {
		return this.creationDate;
		
	}
	
	 /**  
	 * Set the value related to the column: creationDate.
	 * @param creationDate the creationDate value you wish to set
	 */
	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	 /**
	 * Return the value associated with the column: deleted.
	 * @return A Boolean object (this.deleted)
	 */
	public Boolean isDeleted() {
		return this.deleted;
		
	}
	

  
	 /**  
	 * Set the value related to the column: deleted.
	 * @param deleted the deleted value you wish to set
	 */
	public void setDeleted(final Boolean deleted) {
		this.deleted = deleted;
	}

	 /**
	 * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
	public Long getId() {
		return this.id;
		
	}
	

  
	 /**  
	 * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Long id) {
		this.id = id;
	}

	 /**
	 * Return the value associated with the column: lastModifiedDate.
	 * @return A Date object (this.lastModifiedDate)
	 */
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}
	

  
	 /**  
	 * Set the value related to the column: lastModifiedDate.
	 * @param lastModifiedDate the lastModifiedDate value you wish to set
	 */
	public void setLastModifiedDate(final Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	 /**
	 * Return the value associated with the column: lastModifiedUser.
	 * @return A Long object (this.lastModifiedUser)
	 */
	public Long getLastModifiedUser() {
		return this.lastModifiedUser;
		
	}
	
	 /**  
	 * Set the value related to the column: lastModifiedUser.
	 * @param lastModifiedUser the lastModifiedUser value you wish to set
	 */
	public void setLastModifiedUser(final Long lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	 /**
	 * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	public String getName() {
		return this.name;
		
	}
	
	 /**  
	 * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	public void setName(final String name) {
		this.name = name;
	}

	 /**
	 * Return the value associated with the column: productVersion.
	 * @return A Set&lt;ProductVersion&gt; object (this.productVersion)
	 */
	public Set<ProductVersionEntity> getProductVersions() {
		return this.productVersions;
		
	}
  
	 /**  
	 * Set the value related to the column: productVersion.
	 * @param productVersion the productVersion value you wish to set
	 */
	public void setProductVersions(final Set<ProductVersionEntity> productVersion) {
		this.productVersions = productVersion;
	}

	 /**
	 * Return the value associated with the column: reportFileLocation.
	 * @return A String object (this.reportFileLocation)
	 */
	public String getReportFileLocation() {
		return this.reportFileLocation;
		
	}
	

  
	 /**  
	 * Set the value related to the column: reportFileLocation.
	 * @param reportFileLocation the reportFileLocation value you wish to set
	 */
	public void setReportFileLocation(final String reportFileLocation) {
		this.reportFileLocation = reportFileLocation;
	}

	 /**
	 * Return the value associated with the column: developer.
	 * @return A Developer object (this.developer)
	 */
	public Long getDeveloperId() {
		return this.developerId;
		
	}
	

  
	 /**  
	 * Set the value related to the column: developer.
	 * @param developer the developer value you wish to set
	 */
	public void setDeveloperId(Long developerId) {
		this.developerId = developerId;
	}


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("creationDate: " + this.getCreationDate() + ", ");
		sb.append("deleted: " + this.isDeleted() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("lastModifiedDate: " + this.getLastModifiedDate() + ", ");
		sb.append("lastModifiedUser: " + this.getLastModifiedUser() + ", ");
		sb.append("name: " + this.getName() + ", ");
		sb.append("reportFileLocation: " + this.getReportFileLocation() + ", ");
		return sb.toString();		
	}
}
