package gov.healthit.chpl.entity;

import gov.healthit.chpl.entity.TestTaskResult;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: test_participant.
 * 
 *
 * @author autogenerated
 */

@Entity
@Table(name = "test_participant", catalog = "openchpl", schema = "openchpl")
public class TestParticipant implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = 8455958919305291495L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Long> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());
	
	/** hashCode temporary storage. */
	private volatile Long hashCode;
	

	/** Field mapping. */
	private Integer age;
	/** Field mapping. */
	private String assistiveTechnologyNeeds;
	/** Field mapping. */
	private Date creationDate;
	/** Field mapping. */
	private Boolean deleted;
	/** Field mapping. */
	private String gender;
	/** Field mapping. */
	private Long id;
	/** Field mapping. */
	private Date lastModifiedDate;
	/** Field mapping. */
	private Long lastModifiedUser;
	/** Field mapping. */
	private String occupation;
	/** Field mapping. */
	private Set<TestTaskResult> testTaskResults = new HashSet<TestTaskResult>();

	/** Field mapping. */
	private TestEventDetails testEventDetails;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public TestParticipant() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public TestParticipant(Long id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param creationDate Date object;
	 * @param deleted Boolean object;
	 * @param id Long object;
	 * @param lastModifiedDate Date object;
	 * @param lastModifiedUser Long object;
	 * @param testEventDetails TestEventDetails object;
	 */
	public TestParticipant(Date creationDate, Boolean deleted, Long id, 					
			Date lastModifiedDate, Long lastModifiedUser, TestEventDetails testEventDetails) {

		this.creationDate = creationDate;
		this.deleted = deleted;
		this.id = id;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedUser = lastModifiedUser;
		this.testEventDetails = testEventDetails;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return TestParticipant.class;
	}
 

	 /**
	 * Return the value associated with the column: age.
	 * @return A Integer object (this.age)
	 */
	public Integer getAge() {
		return this.age;
		
	}
	

  
	 /**  
	 * Set the value related to the column: age.
	 * @param age the age value you wish to set
	 */
	public void setAge(final Integer age) {
		this.age = age;
	}

	 /**
	 * Return the value associated with the column: assistiveTechnologyNeeds.
	 * @return A String object (this.assistiveTechnologyNeeds)
	 */
	@Basic( optional = true )
	@Column( name = "assistive_technology_needs", length = 250  )
	public String getAssistiveTechnologyNeeds() {
		return this.assistiveTechnologyNeeds;
		
	}
	

  
	 /**  
	 * Set the value related to the column: assistiveTechnologyNeeds.
	 * @param assistiveTechnologyNeeds the assistiveTechnologyNeeds value you wish to set
	 */
	public void setAssistiveTechnologyNeeds(final String assistiveTechnologyNeeds) {
		this.assistiveTechnologyNeeds = assistiveTechnologyNeeds;
	}

	 /**
	 * Return the value associated with the column: creationDate.
	 * @return A Date object (this.creationDate)
	 */
	@Basic( optional = false )
	@Column( name = "creation_date", nullable = false  )
	public Date getCreationDate() {
		return this.creationDate;
		
	}
	

  
	 /**  
	 * Set the value related to the column: creationDate.
	 * @param creationDate the creationDate value you wish to set
	 */
	public void setCreationDate(final Date creationDate) {
		this.creationDate = creationDate;
	}

	 /**
	 * Return the value associated with the column: deleted.
	 * @return A Boolean object (this.deleted)
	 */
	@Basic( optional = false )
	@Column( nullable = false  )
	public Boolean isDeleted() {
		return this.deleted;
		
	}
	

  
	 /**  
	 * Set the value related to the column: deleted.
	 * @param deleted the deleted value you wish to set
	 */
	public void setDeleted(final Boolean deleted) {
		this.deleted = deleted;
	}

	 /**
	 * Return the value associated with the column: gender.
	 * @return A String object (this.gender)
	 */
	@Basic( optional = true )
	@Column( length = 1  )
	public String getGender() {
		return this.gender;
		
	}
	

  
	 /**  
	 * Set the value related to the column: gender.
	 * @param gender the gender value you wish to set
	 */
	public void setGender(final String gender) {
		this.gender = gender;
	}

	 /**
	 * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "testParticipantTest_paticipant_idGenerator")
	@Basic( optional = false )
	@Column( name = "test_paticipant_id", nullable = false  )
	@SequenceGenerator(name = "testParticipantTest_paticipant_idGenerator", sequenceName = "openchpl.openchpl.test_participant_test_paticipant_id_seq", schema = "openchpl", catalog = "openchpl")
	public Long getId() {
		return this.id;
		
	}
	

  
	 /**  
	 * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Long id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0L) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

	 /**
	 * Return the value associated with the column: lastModifiedDate.
	 * @return A Date object (this.lastModifiedDate)
	 */
	@Basic( optional = false )
	@Column( name = "last_modified_date", nullable = false  )
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
		
	}
	

  
	 /**  
	 * Set the value related to the column: lastModifiedDate.
	 * @param lastModifiedDate the lastModifiedDate value you wish to set
	 */
	public void setLastModifiedDate(final Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	 /**
	 * Return the value associated with the column: lastModifiedUser.
	 * @return A Long object (this.lastModifiedUser)
	 */
	@Basic( optional = false )
	@Column( name = "last_modified_user", nullable = false  )
	public Long getLastModifiedUser() {
		return this.lastModifiedUser;
		
	}
	

  
	 /**  
	 * Set the value related to the column: lastModifiedUser.
	 * @param lastModifiedUser the lastModifiedUser value you wish to set
	 */
	public void setLastModifiedUser(final Long lastModifiedUser) {
		this.lastModifiedUser = lastModifiedUser;
	}

	 /**
	 * Return the value associated with the column: occupation.
	 * @return A String object (this.occupation)
	 */
	@Basic( optional = true )
	@Column( length = 50  )
	public String getOccupation() {
		return this.occupation;
		
	}
	

  
	 /**  
	 * Set the value related to the column: occupation.
	 * @param occupation the occupation value you wish to set
	 */
	public void setOccupation(final String occupation) {
		this.occupation = occupation;
	}

	 /**
	 * Return the value associated with the column: testTaskResult.
	 * @return A Set&lt;TestTaskResult&gt; object (this.testTaskResult)
	 */
 	@OneToMany( fetch = FetchType.LAZY, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "testPaticipant"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@Column( name = "test_paticipant_id", nullable = false  )
	public Set<TestTaskResult> getTestTaskResults() {
		return this.testTaskResults;
		
	}
	
	/**
	 * Adds a bi-directional link of type TestTaskResult to the testTaskResults set.
	 * @param testTaskResult item to add
	 */
	public void addTestTaskResult(TestTaskResult testTaskResult) {
		testTaskResult.setTestPaticipant(this);
		this.testTaskResults.add(testTaskResult);
	}

  
	 /**  
	 * Set the value related to the column: testTaskResult.
	 * @param testTaskResult the testTaskResult value you wish to set
	 */
	public void setTestTaskResults(final Set<TestTaskResult> testTaskResult) {
		this.testTaskResults = testTaskResult;
	}

	 /**
	 * Return the value associated with the column: testEventDetails.
	 * @return A TestEventDetails object (this.testEventDetails)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@JoinColumn(name = "test_event_details_id", nullable = false )
	public TestEventDetails getTestEventDetails() {
		return this.testEventDetails;
		
	}
	

  
	 /**  
	 * Set the value related to the column: testEventDetails.
	 * @param testEventDetails the testEventDetails value you wish to set
	 */
	public void setTestEventDetails(final TestEventDetails testEventDetails) {
		this.testEventDetails = testEventDetails;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public TestParticipant clone() throws CloneNotSupportedException {
		
        final TestParticipant copy = (TestParticipant)super.clone();

		copy.setAge(this.getAge());
		copy.setAssistiveTechnologyNeeds(this.getAssistiveTechnologyNeeds());
		copy.setCreationDate(this.getCreationDate());
		copy.setDeleted(this.isDeleted());
		copy.setGender(this.getGender());
		copy.setId(this.getId());
		copy.setLastModifiedDate(this.getLastModifiedDate());
		copy.setLastModifiedUser(this.getLastModifiedUser());
		copy.setOccupation(this.getOccupation());
		if (this.getTestTaskResults() != null) {
			copy.getTestTaskResults().addAll(this.getTestTaskResults());
		}
		copy.setTestEventDetails(this.getTestEventDetails());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("age: " + this.getAge() + ", ");
		sb.append("assistiveTechnologyNeeds: " + this.getAssistiveTechnologyNeeds() + ", ");
		sb.append("creationDate: " + this.getCreationDate() + ", ");
		sb.append("deleted: " + this.isDeleted() + ", ");
		sb.append("gender: " + this.getGender() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("lastModifiedDate: " + this.getLastModifiedDate() + ", ");
		sb.append("lastModifiedUser: " + this.getLastModifiedUser() + ", ");
		sb.append("occupation: " + this.getOccupation() + ", ");
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final TestParticipant that; 
		try {
			that = (TestParticipant) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAge() == null) && (that.getAge() == null)) || (getAge() != null && getAge().equals(that.getAge())));
		result = result && (((getAssistiveTechnologyNeeds() == null) && (that.getAssistiveTechnologyNeeds() == null)) || (getAssistiveTechnologyNeeds() != null && getAssistiveTechnologyNeeds().equals(that.getAssistiveTechnologyNeeds())));
		result = result && (((getCreationDate() == null) && (that.getCreationDate() == null)) || (getCreationDate() != null && getCreationDate().equals(that.getCreationDate())));
		result = result && (((isDeleted() == null) && (that.isDeleted() == null)) || (isDeleted() != null && isDeleted().equals(that.isDeleted())));
		result = result && (((getGender() == null) && (that.getGender() == null)) || (getGender() != null && getGender().equals(that.getGender())));
		result = result && (((getLastModifiedDate() == null) && (that.getLastModifiedDate() == null)) || (getLastModifiedDate() != null && getLastModifiedDate().equals(that.getLastModifiedDate())));
		result = result && (((getLastModifiedUser() == null) && (that.getLastModifiedUser() == null)) || (getLastModifiedUser() != null && getLastModifiedUser().equals(that.getLastModifiedUser())));
		result = result && (((getOccupation() == null) && (that.getOccupation() == null)) || (getOccupation() != null && getOccupation().equals(that.getOccupation())));
		result = result && (((getTestEventDetails() == null) && (that.getTestEventDetails() == null)) || (getTestEventDetails() != null && getTestEventDetails().getId().equals(that.getTestEventDetails().getId())));	
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Long newHashCode = null;

					if ( getId() != null ) {
					newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0L) {
							newHashCode = getId();
						} else {
							newHashCode = (long) super.hashCode();

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
		return (int) (this.hashCode & 0xffffff);
	}
	

	
}
